// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhachSan.Models;

#nullable disable

namespace QuanLyKhachSan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231118093216_AddDataAbdTableToDb")]
    partial class AddDataAbdTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhachSan.Models.ChiTietDichVu", b =>
                {
                    b.Property<string>("MaDichVu")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnOrder(0);

                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnOrder(1);

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianDichVu")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDichVu", "MaKhachHang");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("ChiTietDichVu");

                    b.HasData(
                        new
                        {
                            MaDichVu = "DV001",
                            MaKhachHang = "KH001",
                            MaNhanVien = "NV001",
                            SoLuong = 2,
                            ThoiGianDichVu = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4195),
                            TrangThai = "Hoàn thành"
                        },
                        new
                        {
                            MaDichVu = "DV002",
                            MaKhachHang = "KH002",
                            MaNhanVien = "NV002",
                            SoLuong = 1,
                            ThoiGianDichVu = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4197),
                            TrangThai = "Chưa hoàn thành"
                        },
                        new
                        {
                            MaDichVu = "DV003",
                            MaKhachHang = "KH003",
                            MaNhanVien = "NV003",
                            SoLuong = 3,
                            ThoiGianDichVu = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4198),
                            TrangThai = "Hoàn thành"
                        },
                        new
                        {
                            MaDichVu = "DV004",
                            MaKhachHang = "KH004",
                            MaNhanVien = "NV004",
                            SoLuong = 2,
                            ThoiGianDichVu = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4200),
                            TrangThai = "Chưa hoàn thành"
                        },
                        new
                        {
                            MaDichVu = "DV005",
                            MaKhachHang = "KH005",
                            MaNhanVien = "NV005",
                            SoLuong = 1,
                            ThoiGianDichVu = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4201),
                            TrangThai = "Hoàn thành"
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DanhGia", b =>
                {
                    b.Property<string>("MaDanhGia")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("BinhLuan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DiemDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DanhGia");

                    b.HasData(
                        new
                        {
                            MaDanhGia = "DG001",
                            BinhLuan = "Dịch vụ tốt, phòng sạch sẽ.",
                            DiemDanhGia = 5,
                            MaKhachHang = "KH001",
                            NgayDanhGia = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4180)
                        },
                        new
                        {
                            MaDanhGia = "DG002",
                            BinhLuan = "Không hài lòng với dịch vụ nhân viên.",
                            DiemDanhGia = 2,
                            MaKhachHang = "KH002",
                            NgayDanhGia = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4181)
                        },
                        new
                        {
                            MaDanhGia = "DG003",
                            BinhLuan = "Phòng ốc quá ồn ào, không yên tĩnh.",
                            DiemDanhGia = 3,
                            MaKhachHang = "KH003",
                            NgayDanhGia = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4182)
                        },
                        new
                        {
                            MaDanhGia = "DG004",
                            BinhLuan = "Dịch vụ và phòng ốc đều rất tốt.",
                            DiemDanhGia = 5,
                            MaKhachHang = "KH004",
                            NgayDanhGia = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4183)
                        },
                        new
                        {
                            MaDanhGia = "DG005",
                            BinhLuan = "Giá cả hợp lý, nhân viên nhiệt tình.",
                            DiemDanhGia = 4,
                            MaKhachHang = "KH005",
                            NgayDanhGia = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4184)
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DatPhong", b =>
                {
                    b.Property<string>("MaDatPhong")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("HinhThucDatPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongNguoiLon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTreEm")
                        .HasColumnType("int");

                    b.Property<int>("SoTienTraTruoc")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TongTienPhong")
                        .HasColumnType("int");

                    b.HasKey("MaDatPhong");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaPhong");

                    b.ToTable("DatPhong");

                    b.HasData(
                        new
                        {
                            MaDatPhong = "DP001",
                            HinhThucDatPhong = "Trực tuyến",
                            MaKhachHang = "KH001",
                            MaNhanVien = "NV001",
                            MaPhong = "P001",
                            NgayNhan = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4154),
                            NgayTra = new DateTime(2023, 11, 19, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4155),
                            SoLuongNguoiLon = 2,
                            SoLuongTreEm = 1,
                            SoTienTraTruoc = 50000,
                            TinhTrang = "Đã xác nhận",
                            TongTienPhong = 100000
                        },
                        new
                        {
                            MaDatPhong = "DP002",
                            HinhThucDatPhong = "Điện thoại",
                            MaKhachHang = "KH002",
                            MaNhanVien = "NV002",
                            MaPhong = "P002",
                            NgayNhan = new DateTime(2023, 11, 20, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4162),
                            NgayTra = new DateTime(2023, 11, 22, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4163),
                            SoLuongNguoiLon = 1,
                            SoLuongTreEm = 0,
                            SoTienTraTruoc = 80000,
                            TinhTrang = "Đã xác nhận",
                            TongTienPhong = 150000
                        },
                        new
                        {
                            MaDatPhong = "DP003",
                            HinhThucDatPhong = "Trực tiếp",
                            MaKhachHang = "KH003",
                            MaNhanVien = "NV003",
                            MaPhong = "P003",
                            NgayNhan = new DateTime(2023, 11, 21, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4165),
                            NgayTra = new DateTime(2023, 11, 23, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4166),
                            SoLuongNguoiLon = 3,
                            SoLuongTreEm = 2,
                            SoTienTraTruoc = 120000,
                            TinhTrang = "Đã xác nhận",
                            TongTienPhong = 200000
                        },
                        new
                        {
                            MaDatPhong = "DP004",
                            HinhThucDatPhong = "Trực tuyến",
                            MaKhachHang = "KH004",
                            MaNhanVien = "NV004",
                            MaPhong = "P004",
                            NgayNhan = new DateTime(2023, 11, 22, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4167),
                            NgayTra = new DateTime(2023, 11, 24, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4168),
                            SoLuongNguoiLon = 2,
                            SoLuongTreEm = 0,
                            SoTienTraTruoc = 150000,
                            TinhTrang = "Đã xác nhận",
                            TongTienPhong = 250000
                        },
                        new
                        {
                            MaDatPhong = "DP005",
                            HinhThucDatPhong = "Điện thoại",
                            MaKhachHang = "KH005",
                            MaNhanVien = "NV005",
                            MaPhong = "P005",
                            NgayNhan = new DateTime(2023, 11, 23, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4169),
                            NgayTra = new DateTime(2023, 11, 25, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4170),
                            SoLuongNguoiLon = 1,
                            SoLuongTreEm = 1,
                            SoTienTraTruoc = 200000,
                            TinhTrang = "Đã xác nhận",
                            TongTienPhong = 300000
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DichVu", b =>
                {
                    b.Property<string>("MaDichVu")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("GiaTien")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("GioBatDauDichVu")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThucDichVu")
                        .HasColumnType("time");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVu");

                    b.HasData(
                        new
                        {
                            MaDichVu = "DV001",
                            DonViTinh = "Cái",
                            GiaTien = 50000,
                            GioBatDauDichVu = new TimeSpan(0, 6, 0, 0, 0),
                            GioKetThucDichVu = new TimeSpan(0, 22, 0, 0, 0),
                            TenDichVu = "Dịch Vụ 1",
                            TinhTrang = "Hoạt động"
                        },
                        new
                        {
                            MaDichVu = "DV002",
                            DonViTinh = "Cái",
                            GiaTien = 80000,
                            GioBatDauDichVu = new TimeSpan(0, 6, 0, 0, 0),
                            GioKetThucDichVu = new TimeSpan(0, 22, 0, 0, 0),
                            TenDichVu = "Dịch Vụ 2",
                            TinhTrang = "Hoạt động"
                        },
                        new
                        {
                            MaDichVu = "DV003",
                            DonViTinh = "Bộ",
                            GiaTien = 120000,
                            GioBatDauDichVu = new TimeSpan(0, 6, 0, 0, 0),
                            GioKetThucDichVu = new TimeSpan(0, 22, 0, 0, 0),
                            TenDichVu = "Dịch Vụ 3",
                            TinhTrang = "Ngừng hoạt động"
                        },
                        new
                        {
                            MaDichVu = "DV004",
                            DonViTinh = "Lần sử dụng",
                            GiaTien = 150000,
                            GioBatDauDichVu = new TimeSpan(0, 6, 0, 0, 0),
                            GioKetThucDichVu = new TimeSpan(0, 22, 0, 0, 0),
                            TenDichVu = "Dịch Vụ 4",
                            TinhTrang = "Hoạt động"
                        },
                        new
                        {
                            MaDichVu = "DV005",
                            DonViTinh = "Bộ",
                            GiaTien = 200000,
                            GioBatDauDichVu = new TimeSpan(0, 6, 0, 0, 0),
                            GioKetThucDichVu = new TimeSpan(0, 22, 0, 0, 0),
                            TenDichVu = "Dịch Vụ 5",
                            TinhTrang = "Hoạt động"
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("MaDatPhong")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("SoTienThanhToan")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("TongTienDichVu")
                        .HasColumnType("int");

                    b.Property<int>("TongTienPhong")
                        .HasColumnType("int");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("HoaDon");

                    b.HasData(
                        new
                        {
                            MaHoaDon = "HD001",
                            MaDatPhong = "DP001",
                            MaNhanVien = "NV001",
                            SoTienThanhToan = 150000,
                            ThoiGianThanhToan = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4137),
                            TongTienDichVu = 50000,
                            TongTienPhong = 100000
                        },
                        new
                        {
                            MaHoaDon = "HD002",
                            MaDatPhong = "DP002",
                            MaNhanVien = "NV002",
                            SoTienThanhToan = 230000,
                            ThoiGianThanhToan = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4139),
                            TongTienDichVu = 80000,
                            TongTienPhong = 150000
                        },
                        new
                        {
                            MaHoaDon = "HD003",
                            MaDatPhong = "DP003",
                            MaNhanVien = "NV003",
                            SoTienThanhToan = 320000,
                            ThoiGianThanhToan = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4140),
                            TongTienDichVu = 120000,
                            TongTienPhong = 200000
                        },
                        new
                        {
                            MaHoaDon = "HD004",
                            MaDatPhong = "DP004",
                            MaNhanVien = "NV004",
                            SoTienThanhToan = 400000,
                            ThoiGianThanhToan = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4141),
                            TongTienDichVu = 150000,
                            TongTienPhong = 250000
                        },
                        new
                        {
                            MaHoaDon = "HD005",
                            MaDatPhong = "DP005",
                            MaNhanVien = "NV005",
                            SoTienThanhToan = 500000,
                            ThoiGianThanhToan = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4142),
                            TongTienDichVu = 200000,
                            TongTienPhong = 300000
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHang");

                    b.HasData(
                        new
                        {
                            MaKhachHang = "KH001",
                            CCCD = "123456789012",
                            DiaChi = "123 Nguyen Van X, Quan 1, TP.HCM",
                            Email = "khachhang1@example.com",
                            GioiTinh = "Nam",
                            MatKhau = "password1",
                            NgayDangKy = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4029),
                            NgaySinh = new DateTime(1992, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "123456789",
                            TenKhachHang = "Nguyen Van X",
                            TinhTrang = "Active"
                        },
                        new
                        {
                            MaKhachHang = "KH002",
                            CCCD = "987654321098",
                            DiaChi = "456 Tran Thi Y, Quan 2, TP.HCM",
                            Email = "khachhang2@example.com",
                            GioiTinh = "Nu",
                            MatKhau = "password2",
                            NgayDangKy = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4032),
                            NgaySinh = new DateTime(1995, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "987654321",
                            TenKhachHang = "Tran Thi Y",
                            TinhTrang = "Active"
                        },
                        new
                        {
                            MaKhachHang = "KH003",
                            CCCD = "111223344055",
                            DiaChi = "789 Le Van Z, Quan 3, TP.HCM",
                            Email = "khachhang3@example.com",
                            GioiTinh = "Nam",
                            MatKhau = "password3",
                            NgayDangKy = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4034),
                            NgaySinh = new DateTime(1988, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "111223344",
                            TenKhachHang = "Le Van Z",
                            TinhTrang = "Inactive"
                        },
                        new
                        {
                            MaKhachHang = "KH004",
                            CCCD = "555666777044",
                            DiaChi = "101 Pham Thi K, Quan 4, TP.HCM",
                            Email = "khachhang4@example.com",
                            GioiTinh = "Nu",
                            MatKhau = "password4",
                            NgayDangKy = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4036),
                            NgaySinh = new DateTime(1990, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "555666777",
                            TenKhachHang = "Pham Thi K",
                            TinhTrang = "Active"
                        },
                        new
                        {
                            MaKhachHang = "KH005",
                            CCCD = "999888777033",
                            DiaChi = "202 Hoang Van M, Quan 5, TP.HCM",
                            Email = "khachhang5@example.com",
                            GioiTinh = "Nam",
                            MatKhau = "password5",
                            NgayDangKy = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4057),
                            NgaySinh = new DateTime(1985, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "999888777",
                            TenKhachHang = "Hoang Van M",
                            TinhTrang = "Active"
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.LoaiPhong", b =>
                {
                    b.Property<string>("MaLoaiPhong")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("GiaPhongTheoNgay")
                        .HasColumnType("int");

                    b.Property<int>("GiaTheoGio")
                        .HasColumnType("int");

                    b.Property<int>("PhuThuTraMuon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNguoiLon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTreEm")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaLoaiPhong");

                    b.ToTable("LoaiPhong");

                    b.HasData(
                        new
                        {
                            MaLoaiPhong = "LP001",
                            GiaPhongTheoNgay = 100000,
                            GiaTheoGio = 50000,
                            PhuThuTraMuon = 20000,
                            SoLuongNguoiLon = 1,
                            SoLuongTreEm = 0,
                            TenLoaiPhong = "Phòng Đơn"
                        },
                        new
                        {
                            MaLoaiPhong = "LP002",
                            GiaPhongTheoNgay = 150000,
                            GiaTheoGio = 80000,
                            PhuThuTraMuon = 25000,
                            SoLuongNguoiLon = 2,
                            SoLuongTreEm = 1,
                            TenLoaiPhong = "Phòng Đôi"
                        },
                        new
                        {
                            MaLoaiPhong = "LP003",
                            GiaPhongTheoNgay = 200000,
                            GiaTheoGio = 120000,
                            PhuThuTraMuon = 30000,
                            SoLuongNguoiLon = 4,
                            SoLuongTreEm = 2,
                            TenLoaiPhong = "Phòng Gia Đình"
                        },
                        new
                        {
                            MaLoaiPhong = "LP004",
                            GiaPhongTheoNgay = 250000,
                            GiaTheoGio = 150000,
                            PhuThuTraMuon = 35000,
                            SoLuongNguoiLon = 3,
                            SoLuongTreEm = 1,
                            TenLoaiPhong = "Phòng Suite"
                        },
                        new
                        {
                            MaLoaiPhong = "LP005",
                            GiaPhongTheoNgay = 300000,
                            GiaTheoGio = 200000,
                            PhuThuTraMuon = 40000,
                            SoLuongNguoiLon = 2,
                            SoLuongTreEm = 0,
                            TenLoaiPhong = "Phòng VIP"
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("AnhNhanVienBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNhanVien");

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            MaNhanVien = "NV001",
                            AnhNhanVienBase64 = "Base64Image1",
                            CCCD = "123456789012",
                            ChucVu = "Quan ly",
                            DiaChi = "123 Nguyen Van A, Quan 1, TP.HCM",
                            Email = "nhanvien1@example.com",
                            GioiTinh = "Nam",
                            MatKhau = "password1",
                            NgayDangKy = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(3925),
                            NgaySinh = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayVaoLam = new DateTime(2021, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(3933),
                            SoDienThoai = "123456789",
                            TenDangNhap = "user1",
                            TenNhanVien = "Nguyen Van A",
                            TinhTrang = "Hoat dong"
                        },
                        new
                        {
                            MaNhanVien = "NV002",
                            AnhNhanVienBase64 = "Base64Image2",
                            CCCD = "987654321098",
                            ChucVu = "Nhan vien",
                            DiaChi = "456 Tran Thi B, Quan 2, TP.HCM",
                            Email = "nhanvien2@example.com",
                            GioiTinh = "Nu",
                            MatKhau = "password2",
                            NgayDangKy = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(3943),
                            NgaySinh = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayVaoLam = new DateTime(2022, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(3944),
                            SoDienThoai = "987654321",
                            TenDangNhap = "user2",
                            TenNhanVien = "Tran Thi B",
                            TinhTrang = "Hoat dong"
                        },
                        new
                        {
                            MaNhanVien = "NV003",
                            AnhNhanVienBase64 = "Base64Image3",
                            CCCD = "111223344055",
                            ChucVu = "Nhan vien",
                            DiaChi = "789 Le Van C, Quan 3, TP.HCM",
                            Email = "nhanvien3@example.com",
                            GioiTinh = "Nam",
                            MatKhau = "password3",
                            NgayDangKy = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(3946),
                            NgaySinh = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayVaoLam = new DateTime(2020, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(3947),
                            SoDienThoai = "111223344",
                            TenDangNhap = "user3",
                            TenNhanVien = "Le Van C",
                            TinhTrang = "Nghi viec"
                        },
                        new
                        {
                            MaNhanVien = "NV004",
                            AnhNhanVienBase64 = "Base64Image4",
                            CCCD = "555666777044",
                            ChucVu = "Quan ly",
                            DiaChi = "101 Pham Thi D, Quan 4, TP.HCM",
                            Email = "nhanvien4@example.com",
                            GioiTinh = "Nu",
                            MatKhau = "password4",
                            NgayDangKy = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(3949),
                            NgaySinh = new DateTime(1988, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayVaoLam = new DateTime(2018, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(3950),
                            SoDienThoai = "555666777",
                            TenDangNhap = "user4",
                            TenNhanVien = "Pham Thi D",
                            TinhTrang = "Hoat dong"
                        },
                        new
                        {
                            MaNhanVien = "NV005",
                            AnhNhanVienBase64 = "Base64Image5",
                            CCCD = "999888777033",
                            ChucVu = "Nhan vien",
                            DiaChi = "202 Hoang Van E, Quan 5, TP.HCM",
                            Email = "nhanvien5@example.com",
                            GioiTinh = "Nam",
                            MatKhau = "password5",
                            NgayDangKy = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(3952),
                            NgaySinh = new DateTime(1980, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayVaoLam = new DateTime(2019, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(3953),
                            SoDienThoai = "999888777",
                            TenDangNhap = "user5",
                            TenNhanVien = "Hoang Van E",
                            TinhTrang = "Hoat dong"
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Phong", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<byte[]>("AnhPhong")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("KhuVuc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaLoaiPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaLoaiPhong");

                    b.ToTable("Phong");

                    b.HasData(
                        new
                        {
                            MaPhong = "P001",
                            AnhPhong = new byte[] { 1, 2, 3 },
                            KhuVuc = "Khu A",
                            MaLoaiPhong = "LP001",
                            NgayTao = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4085),
                            TinhTrang = "Trong"
                        },
                        new
                        {
                            MaPhong = "P002",
                            AnhPhong = new byte[] { 4, 5, 6 },
                            KhuVuc = "Khu A",
                            MaLoaiPhong = "LP002",
                            NgayTao = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4101),
                            TinhTrang = "Trong"
                        },
                        new
                        {
                            MaPhong = "P003",
                            AnhPhong = new byte[] { 7, 8, 9 },
                            KhuVuc = "Khu B",
                            MaLoaiPhong = "LP003",
                            NgayTao = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4104),
                            TinhTrang = "Da Dat"
                        },
                        new
                        {
                            MaPhong = "P004",
                            AnhPhong = new byte[] { 10, 11, 12 },
                            KhuVuc = "Khu C",
                            MaLoaiPhong = "LP004",
                            NgayTao = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4106),
                            TinhTrang = "Trong"
                        },
                        new
                        {
                            MaPhong = "P005",
                            AnhPhong = new byte[] { 13, 14, 15 },
                            KhuVuc = "Khu C",
                            MaLoaiPhong = "LP005",
                            NgayTao = new DateTime(2023, 11, 18, 16, 32, 16, 287, DateTimeKind.Local).AddTicks(4108),
                            TinhTrang = "Da Dat"
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.ChiTietDichVu", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DanhGia", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DatPhong", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.HoaDon", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Phong", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.LoaiPhong", "LoaiPhong")
                        .WithMany()
                        .HasForeignKey("MaLoaiPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhong");
                });
#pragma warning restore 612, 618
        }
    }
}
